# Generated by Django 2.2.10 on 2020-05-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clubs', models.ManyToManyField(to='class_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Zoom_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('camera', models.BooleanField()),
                ('content', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.School')),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tweet_link', models.CharField(blank=True, max_length=200, null=True)),
                ('inst_link', models.CharField(blank=True, max_length=200, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.School')),
            ],
        ),
    ]
