# Generated by Django 2.2.10 on 2020-05-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom_list',
            name='datetime',
            field=models.CharField(max_length=100),
        ),
    ]
