# Generated by Django 2.2.10 on 2020-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_list',
            name='url',
            field=models.CharField(default='https://www.amazon.co.jp/', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoom_list',
            name='camera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoom_list',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
