# Generated by Django 3.0.5 on 2020-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_formmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormKgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('camera', models.BooleanField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormKuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('camera', models.BooleanField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormRuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('camera', models.BooleanField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FormModel',
            new_name='FormDuModel',
        ),
    ]
