# Generated by Django 3.0.5 on 2020-04-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_auto_20200427_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('camera', models.BooleanField()),
                ('content', models.TextField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_app.School')),
            ],
        ),
        migrations.DeleteModel(
            name='FormDuModel',
        ),
        migrations.DeleteModel(
            name='FormKgModel',
        ),
        migrations.DeleteModel(
            name='FormKuModel',
        ),
        migrations.DeleteModel(
            name='FormRuModel',
        ),
    ]
